name: Generate Docs For library

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Library name"
        required: true
        default: "spotify"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Server Deployment via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # The command here is simply the library name.
          # The forced command in authorized_keys will override the command and
          # invoke /usr/bin/sudo /opt/qilletni/run_docs_wrapper.sh, which reads
          # SSH_ORIGINAL_COMMAND. In this case, SSH_ORIGINAL_COMMAND will be the library name.
          script: ${{ github.event.inputs.library }}
